{{- if .Values.mainnet.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: sonic-extractor-coordinator-mainnet
  name: sonic-extractor-coordinator-mainnet
  namespace: {{ .Values.mainnet.namespace }}
spec:
  replicas: {{ .Values.mainnet.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sonic-extractor-coordinator-mainnet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonic-extractor-coordinator-mainnet
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: sonic-extractor-coordinator
          image: {{ .Values.mainnet.image.repository }}:{{ .Values.mainnet.image.tag }}
          env:
            - name: NODE_ADDRESS
              value: {{ .Values.mainnet.env.node_address }}
            - name: FALLBACK_NODE_ADDRESS
              value: {{ .Values.mainnet.env.fallback_node_address }}
            - name: GCP_PROJECT_ID
              value: {{ .Values.mainnet.env.gcp_project_id }}
            - name: NETWORK
              value: {{ .Values.mainnet.env.network }}
      restartPolicy: Always
{{- end }}
---
{{- if .Values.testnet.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: sonic-extractor-coordinator-testnet
  name: sonic-extractor-coordinator-testnet
  namespace: {{ .Values.testnet.namespace }}
spec:
  replicas: {{ .Values.testnet.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: sonic-extractor-coordinator-testnet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sonic-extractor-coordinator-testnet
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: sonic-extractor-coordinator
        image: {{ .Values.testnet.image.repository }}:{{ .Values.testnet.image.tag }}
        env:
          - name: NODE_ADDRESS
            value: {{ .Values.testnet.env.node_address }}
          - name: FALLBACK_NODE_ADDRESS
            value: {{ .Values.testnet.env.fallback_node_address }}
          - name: GCP_PROJECT_ID
            value: {{ .Values.testnet.env.gcp_project_id }}
          - name: NETWORK
            value: {{ .Values.testnet.env.network }}
      restartPolicy: Always
{{- end }}