# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubsub_range.proto
# Protobuf Python Version: 4.25.6
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pubsub_range.proto\x12\x0b\x65tl.request\"\xbf\x01\n\x0fIndexingRequest\x12\r\n\x05start\x18\x01 \x02(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x02(\x04\x12\x14\n\x06\x62locks\x18\x03 \x02(\x08:\x04true\x12\x12\n\x04logs\x18\x04 \x02(\x08:\x04true\x12\x1a\n\x0ctransactions\x18\x05 \x02(\x08:\x04true\x12\x16\n\x08receipts\x18\x06 \x02(\x08:\x04true\x12\x1c\n\x0e\x64\x65\x63oded_events\x18\x07 \x02(\x08:\x04true\x12\x14\n\x06traces\x18\x08 \x02(\x08:\x04true')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_range_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INDEXINGREQUEST']._serialized_start=36
  _globals['_INDEXINGREQUEST']._serialized_end=227
# @@protoc_insertion_point(module_scope)
